### ISSUE TITLE
仅限 浙江移动 吗

### ISSUE THREAD

**Issue by BlueHtml** [QikaiXu/migu-sign#4]

**Comment by QikaiXu** [comment]
你可以下载咪咕爱看手动签到试试，我也忘了是不是仅限浙江的

**Comment by BlueHtml** [comment]
> 你可以下载咪咕爱看手动签到试试，我也忘了是不是仅限浙江的

我是山西移动，登录后，没有签到的地方，只有个携号转网的页面...

**Comment by QikaiXu** [comment]
咪咕爱看，在个人中心签到，要是还是没有，那可能就只有浙江的。。
