### ISSUE TITLE
请问cookie有效期多长呀？

### ISSUE THREAD

**Issue by Dimlitter** [QikaiXu/migu-sign#5]
好久没用了，问一下ck有效期多长？
之前（快一年前）我绑的时候好像ck只有一天有效期...？
> 考虑出二进制文件部署和docker版吗？github的ip会不会不太安全？
> 大佬可以留个联系方式吗：）

**Comment by Dimlitter** [comment]
哎呀呀呀 刚刚看了一下你的profile...居然是学长...我天

**Comment by QikaiXu** [comment]
过期时间记得挺久的，但是我印象里似乎最多在服务器保留5个cookie，多了之后会清除之前的，具体逻辑没了解过
然后这就是个小脚本，没必要搞个文件或者docker吧，
github的ip安不安全不了解，但是cookie存在github的secret是安全的
联系方式的话，profile里我记得我写了邮箱，能搜到我q

**Comment by Dimlitter** [comment]
我的意思是github action跑的时候不是美国ip么..不会有风控...?
我建议增加二进制文件和docker版也是出于这个考虑🙈
