### ISSUE TITLE
你好，手机没有Root，能抓到https的接口吗？

### ISSUE THREAD

**Issue by xlzy520** [QikaiXu/migu-sign#7]

**Comment by QikaiXu** [comment]
可以的

**Comment by xlzy520** [comment]
@QikaiXu 请教一下如何做到，我网上搜了很多教程，都去尝试过，都没有成功。原因好像是现在的安卓无法把用户添加的证书当做根证书了，想要当做根证书，需要root。
所以我想问问你的方案是什么。

**Comment by xlzy520** [comment]
大佬可以把你的微信号发我邮箱吗？
1017866168@qq.com

**Comment by QikaiXu** [comment]
加我这个邮箱的q就行
